name: Despliegue Automatico Footlink

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install --force

      - name: Construir la aplicacion
        run: npm run build

      - name: Desplegar a Nginx
        run: rsync -av --delete ./dist/ /home/orangepi/Food-link/footlink/dist/

      - name: Desplegar servidor API
        run: |
          rsync -av ./server/ /home/orangepi/Food-link/footlink/server/
          pm2 restart foodlink-api || true
